name: Run Eslint & Vitest Tests

on:
  push: # This workflow will run on pushes to the main branch
    branches: [ main ]
  pull_request: # This workflow will run on pull requests targeting the main branch
    branches: [ main ]
 
jobs: # Run Vitest tests for TypeScript and JavaScript
  lint-and-vitest: 
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code # Gives access for the ubuntu runner to the repository code
        uses: actions/checkout@v4

      - name: Use Node.js # Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18 

      - name: Install dependencies # Install project dependencies
        run: npm ci

      - name: Run ESLint # Run ESLint to check code quality
        run: npm run lint  
        
      - name: Run tests # Run Vitest tests (vitest.config.ts & vitest.config.js is used for configuration)
        run: npm test\

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/twebsite:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/twebsite:latest